[package]
name = "ldap3_lber"
description = "An ASN.1/BER parser/encoder based on nom"

version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

license = "MIT"
categories = ["encoding", "parsing"]
keywords = ["ASN1", "BER", "nom"]
documentation = "https://docs.rs/ldap3_lber"

[dependencies]
bytes.workspace = true
nom.workspace = true
